ADVANCED:
  JOBS: 16
Build Info:
  TARGET: i686-elf
Toolchain Versions:
  BINUTILS_VERSION: '2.44'
  GCC_VERSION: 15.1.0
Urls:
  BINUTILS_URL: https://ftp.gnu.org/gnu/binutils/binutils-BINUTILS_VERSION.tar.gz
  GCC_URL: https://ftp.gnu.org/gnu/gcc/gcc-15.1.0/gcc-GCC_VERSION.tar.gz
